@startuml

skinparam class {
	ArrowColor black
	BorderColor black
}

skinparam stereotypeCBackgroundColor YellowGreen
skinparam shadowing false

class Main #ffffff

Main *-- field.Field
Main *-- CardField


''' Про это смотри cards.puml, тут очень упощеная ее часть
class CardField #cccccc
CardField *-- Card


class Card #cccccc
Card *-- field.Creature
Card *-- field.Area
Card *-- CardView


class CreatureCardView #CAD0E8
CardView <|-- CreatureCardView


class AreaCardView #CAD0E8
CardView <|-- AreaCardView


abstract class CardView #ffffff
CardView --> PhaserWrapper


class PhaserWrapper #ffffff {
    + game
}
PhaserWrapper --> phaser.game


package "field" {
    abstract class FieldManager #ffffff


    abstract class FieldObjectView #ffffff
    FieldObjectView <|-up- TileView
    FieldObjectView <|-up- CreatureView
    FieldObjectView <|-up- AreaView
    FieldObjectView --> .PhaserWrapper


    class Field #ffffff {
        - pickedCreature: Creature
    }
    Field *-- TileManager
    Field *-- FieldObjectManager


    '''Tile'''
    class TileManager #F7CDFF
    FieldManager <|-- TileManager
    TileManager *-- Tile


    class Tile #F7CDFF
    Tile *-- TileView


    class TileView #F7CDFF


    '''Creature'''
    class FieldObjectManager #CAD0E8 {
        - creatureList
        - areaList
        + goToPosition(creature: Creature, x, y)
        + attack(creature1: Creature, creature2: Creature)
    }
    FieldManager <|-- FieldObjectManager
    FieldObjectManager *-- Creature


    class Creature #CAD0E8 {
        + attack(creature: Creature)
        + takeDamage(damage: int)
    }
    Creature *-- CreatureView


    class CreatureView #CAD0E8


    '''Area'''
    FieldObjectManager *-- Area


    class Area #D6E8CA
    Area *-- AreaView


    class AreaView #D6E8CA

}


package "phaser" #DDDDDD {
    class game
}
@enduml
