@startuml

'Палитра
'#D6E8CA
'#CAD0E8
'#F7CDFF

skinparam class {
	ArrowColor black
	BorderColor black
}

skinparam stereotypeCBackgroundColor YellowGreen
skinparam shadowing false

class Main #ffffff

Main *-- field.Field
Main *-- CardField


''' Про это смотри cards.puml, тут очень упощеная ее часть
class CardField #fff
CardField *-- Card


class Card #fff
Card *-- field.CreatureView
Card *-- field.AreaView
Card *-- CardView



abstract class CardView #CAD0E8
CardView --> PhaserWrapper


class CreatureCardView #CAD0E8
CardView <|-- CreatureCardView


class AreaCardView #CAD0E8
CardView <|-- AreaCardView


class PhaserWrapper #ffffff {
    + game
}
PhaserWrapper --> phaser.game


package "field" {
    class Field #ffffff {
        - pickedCreature: Creature
    }
    Field *-- FieldObjectManager
    Field *-- TileView
    Field --> .CardField


    class FieldObjectManager #fff {
        - creatureList
        - areaList
        + goToPosition(creature: Creature, x, y)
    }
    FieldObjectManager --> .Card



    abstract class FieldObjectView #D6E8CA
    FieldObjectView <|-left- TileView
    FieldObjectView <|-down- CreatureView
    FieldObjectView <|-down- AreaView
    FieldObjectView --> .PhaserWrapper

    class CreatureView #D6E8CA
    class AreaView #D6E8CA
    class TileView #D6E8CA
}


package "phaser" #DDDDDD {
    class game #fff
}
@enduml
