@startuml

skinparam class {
	ArrowColor black
	BorderColor black
}

skinparam stereotypeCBackgroundColor YellowGreen
skinparam shadowing false

package "gama" {
    abstract class BaseManager #ffffff


    abstract class FieldObjectsView #ffffff
    FieldObjectsView <|-up- TileView
    FieldObjectsView <|-up- CreatureView
    FieldObjectsView <|-up- AreaView


    abstract class CardView #ffffff
    
    
    class Main #ffffff
    Main *-- PhaserGame
    Main *-- GameField
    Main *-- CardViewManager


    class PhaserGame #ffffff {
        + game
    }
    PhaserGame --> phaser.game


    class GameField #ffffff {
        - pickedCreature: Creature
    }
    GameField *-- TileManager
    GameField *-- CreatureManager
    GameField *-- AreaManager


    class CardViewManager #ffffff
    CardViewManager --> CardView


    '''Tile'''
    class TileManager #F7CDFF
    BaseManager <|-- TileManager
    TileManager *-- Tile


    class Tile #F7CDFF
    Tile *-- TileView


    class TileView #F7CDFF
    TileView --> PhaserGame


    '''Creature'''
    class CreatureManager #CAD0E8 {
        - creatureList
        + goToPosition(creature: Creature, x, y)
        + attack(creature1: Creature, creature2: Creature)
    }
    BaseManager <|-- CreatureManager
    CreatureManager *-- Creature


    class Creature #CAD0E8 {
        + attack(creature: Creature)
        + takeDamage(damage: int)
    }
    Creature *-- CreatureView
    Creature *-- CreatureCardView


    class CreatureView #CAD0E8
    CreatureView --> PhaserGame


    class CreatureCardView #CAD0E8
    CardView <|-right- CreatureCardView
    CreatureCardView --> PhaserGame


    '''Area'''
    class AreaManager #D6E8CA
    BaseManager <|-- AreaManager
    AreaManager *-- Area


    class Area #D6E8CA
    Area *-- AreaView
    Area *-- AreaCardView


    class AreaView #D6E8CA
    AreaView --> PhaserGame


    class AreaCardView #D6E8CA
    CardView <|-right- AreaCardView
    AreaCardView --> PhaserGame
}


package "phaser" #DDDDDD {
    class game
}
@enduml