@startuml

skinparam class {
	ArrowColor black
	BorderColor black
}

skinparam stereotypeCBackgroundColor YellowGreen
skinparam shadowing false


class CardManager
CardManager --> HandView
CardManager --> TableView
CardManager --> DeckView
CardManager --> GraveyardView


abstract BaseCardView

abstract BaseCardViewManager

class CreatureCardView
BaseCardView <|-- CreatureCardView


class AreaCardView
BaseCardView <|-- AreaCardView


class HandView
HandView --> BaseCardView
BaseCardViewManager <|-- HandView


class TableView
TableView --> BaseCardView
BaseCardViewManager <|-- TableView


class DeckView
DeckView --> BaseCardView
BaseCardViewManager <|-- DeckView


class GraveyardView
GraveyardView --> BaseCardView
BaseCardViewManager <|-- GraveyardView


'class Deck
'class Graveyard


@enduml
